CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    account_id VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bank_account (
    account_id VARCHAR(50) PRIMARY KEY,
    account_type VARCHAR(20) NOT NULL,
    account_holder_name VARCHAR(100) NOT NULL,
    balance DECIMAL(15, 2) NOT NULL,
    version INT DEFAULT 0
);

CREATE TABLE transaction_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    transaction_time TIMESTAMP NOT NULL,
    source_account_id VARCHAR(50),
    destination_account_id VARCHAR(50),
    risk_score INT NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    flagged BOOLEAN NOT NULL
);

CREATE TABLE fraud_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(50) NOT NULL,
    risk_score INT NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    triggered_rules VARCHAR(1000),
    reasons VARCHAR(2000),
    created_at TIMESTAMP NOT NULL
);
